# Generated by Django 4.1.13 on 2025-03-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "long_url",
                    models.URLField(
                        help_text="The original URL to be shortened", max_length=2048
                    ),
                ),
                (
                    "short_url",
                    models.CharField(
                        db_index=True,
                        help_text="The shortened URL identifier",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the URL was created",
                    ),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the URL was last accessed",
                    ),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times the URL has been accessed"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the shortened URL is active"
                    ),
                ),
            ],
            options={
                "verbose_name": "URL",
                "verbose_name_plural": "URLs",
                "ordering": ["-created_at"],
            },
        ),
    ]
